### PR TITLE
Test Suite 1.0 and Travis CI testment

### PR DESCRIPTION
**Pull request by mytja**
Supports both Python 2 and Python 3.
Tested and working for me!
Hope you'll like it! :-)

### CODE REVIEW

**Comment by mytja** [comment]
So that I can help you a bit with testing!
There will be newer versions of it, this is only an basic test suite!

**Comment by mytja** [comment]
Added also Travis CI testment, you can remove it if you want to!

**Comment by mytja** [comment]
And also, I would like to ask you something!
How do you push releases to PyPI?
I have some libraries, that I want to push, but no tutorial works for me?
Thank you so much

**Comment by alexmercerind** [comment]
Hi @mytja !

I looked the process of uploading packages to PyPI [here](https://packaging.python.org/tutorials/packaging-projects/)...

Thankyou!
(I'll review the changes soon, I'm kinda busy today. Hope it helps.)

**Comment by mytja** [comment]
Hello!
It works now! Here is first package: https://pypi.org/project/String-to-Integer/
You don't have to hurry with checking/reviewing! ;-)
Thank you so much
mytja

**Comment by mytja** [comment]
Did you forget to merge it?
Thank you

**Pull request closed without merging**
