### PR TITLE
add publishDate and uploadDate details to Video

### PR DESCRIPTION
**Pull request by AlexandreOuellet**
Pretty much what the title says.

### CODE REVIEW

**Comment by alexmercerind** [comment]
Thanks for your PR submission!

I appreciate your contribution.

**Review by alexmercerind — APPROVED** [review]

**Comment by AlexandreOuellet** [comment]
The printed example seems to only contain an example for getFormats, so I did not update this part, but maybe it would be nice to have that somewhere

**Comment by alexmercerind** [comment]
Surely.

**Comment by AlexandreOuellet** [comment]
Also, what is your release schedule?  When do you bump the version and release on pypi?

**Comment by alexmercerind** [comment]
@AlexandreOuellet sorry, I got bit late in updating library on PyPI.

Now, I've added v1.3.6

**Pull request merged**
