### PR TITLE
Add Transcript & Channel class

### PR DESCRIPTION
**Pull request by mytja**
So, YouTube has added transcription (slovenian "Prepis"). Now we have Transcription classes with really minimal code.
image

Have added tests, but adding you as reviewers as you never know what you can find :wink:.

### CODE REVIEW

**Review by alexmercerind — APPROVED** [review]
Works for me! 💚

Well, we surely have a lot of features in this library.

**Review by raitonoberu — APPROVED** [review]
It works well, great job! Just a couple of comments:
- If subtitles are disabled in the video, it raises the `Failed to extract key` exception. It would be nice to add a proper way to handle this. Maybe just return an empty dict?
- Now it returns transcriptions in English. How about adding a language selection option?

**Comment by mytja** [comment]
> - If subtitles are disabled in the video, it raises the `Failed to extract key` exception. It would be nice to add a proper way to handle this. Maybe just return an empty dict?

This I will certainly fix, but I haven't got an example of video like this.

> - Now it returns transcriptions in English. How about adding a language selection option?

Will have a look.

**Comment by raitonoberu** [comment]
> I haven't got an example of video like this.

Mostly various music videos: https://www.youtube.com/watch?v=hzpt3fQjY9U

**Comment by mytja** [comment]
Done.
Now user can retrieve different languages using `params` parameter, which I give them for specific language.

**Comment by mytja** [comment]
I've also added Channel class, which displays channel info - Resolves #164

**Comment by mytja** [comment]
Will merge this tomorrow

**Pull request merged**
