### PR TITLE
Add HTML request to retrieve publishDate and uploadDate - Resolves #144

### LINKED ISSUE #144: Regression: Cannot retrieve upload_date or publish_date
By using following script and `git bisect start && git bisect good v1.5.1 && git bisect bad main && git bisect run ./check.py`, I found that the commit 31dfb19 introduced this regression:
```python3
#!/usr/bin/env python3
import sys
from youtubesearchpython import Video

info = Video.getInfo("https://www.youtube.com/watch?v=9eQfJqWLXwY") # example video which is quite new
sys.exit(0 if (info.get("uploadDate") or info.get("publishDate")) is not None else 1)
```

The commit 31dfb19 was introduced by PR #142, which fixed #134. In the PR, the author stated YouTube suddenly does not give this information in a common way. However older versions of youtubesearchpython can still extract these dates, even on newer videos.

I really don't know how to fix this while keeping the fix for #134, but maybe this information is helpful to someone else

### PR DESCRIPTION
**Pull request by mytja**
#144

### CODE REVIEW

**Comment by mytja** [comment]
@Zocker1999NET May you test it? Tests are passing. Is that what you wanted?

**Comment by Zocker1999NET** [comment]
Thanks for your work, with this patch and using `enableHTML=True` my tests pass too.

It still makes the whole extraction process slower and it uses up more unnecessary resources (for my case) on the network and YouTube, so I am still considering to stay at a version without the fixes of #134 because this issue does not really affect me.

It may be could be considered for a future version that there are some users, which need the upload date, and some, which prefer to receive working direct stream URLs. Then for example, a call to this library could look like `Video.getInfo(video_url, get_release_date=True, get_stream_urls=False)` (for my case) and the library could decide on requiring only one plain HTML request to do. But this is only an idea.

Still, this is better than before, so thank you. Please merge this change, maybe I will code something like that idea later on.

**Comment by mytja** [comment]
Okay, so here it is.

Now it's like this:
- Video.getFormats() uses InnerTube API, and you cannot change that
- Video.getInfo() uses HTML, and you cannot change that
- Video.get() uses InnerTube API by default, but you can also create a HTML request to YouTube using `get_upload_date=True`

I will merge it, as tests are passing, and it seems to work just fine.

**Comment by Zocker1999NET** [comment]
@mytja that makes even more sense for a good backwards compatibility, thanks for your work

**Pull request merged**
